# eslint-disable no-irregular-whitespace, yaml/no-irregular-whitespace
# prettier-ignore
name:  

run-name: Deploy ${{ inputs.ref || github.ref_name }}

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: "Force checkout a specific git ref (branch, tag, commit)"
        type: string

concurrency:
  group: deploy
  cancel-in-progress: false # canceling could break state

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: pnpm install
        uses: falcondev-it/.github/actions/pnpm-install@master
        with:
          ref: ${{ inputs.ref }}
          registry-url: https://registry.npmjs.org

      - name: Publish
        run: pnpm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
