# eslint-disable no-irregular-whitespace, yaml/no-irregular-whitespace
# prettier-ignore
name:  

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Force checkout a specific git ref (branch, tag, commit)"
        type: string
        default: 'master'

  workflow_call:
    inputs:
      ref:
        description: "Force checkout a specific git ref (branch, tag, commit)"
        type: string

concurrency:
  group: deploy
  cancel-in-progress: false # canceling could break state

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - run: pnpm install --frozen-lockfile

      - name: Publish
        run: pnpm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
